### PR TITLE
Merge thunks and actions into `summaryActions`

### PR DESCRIPTION
**Pull request by siefkenj**
* Merge thunks and actions into `summaryActions`
* Migrates `messages` actions to the RTK-based `createSlice` style.

Several of the reducers were refactors using modern Javascript.

The `msgSetIsJunk` should have the same functionality as the original code, but it seems wrong to me...Is this an unnoticed bug?

### CODE REVIEW

**Review by Standard8 — COMMENTED** [review]
Thank you for this, it is looking good.

Can you explain what you mean by this please? I couldn't quite work out what you're referring to:

> The msgSetIsJunk should have the same functionality as the original code, but it seems wrong to me...Is this an unnoticed bug?

**Comment by siefkenj** [comment]
> Thank you for this, it is looking good.
> 
> Can you explain what you mean by this please? I couldn't quite work out what you're referring to:
> 
> > The msgSetIsJunk should have the same functionality as the original code, but it seems wrong to me...Is this an unnoticed bug?

The original code is

```javascript
   case "MARK_AS_JUNK": {
      // This action should only be activated when the conversation is not a
      //  conversation in a tab AND there's only one message in the conversation,
      //  i.e. the currently selected message
      browser.conversations
        .markSelectedAsJunk(action.isJunk)
        .catch(console.error);
      if (!action.isJunk) {
        // TODO: We should possibly wait until we get the notification before
        // clearing the state here.
        return modifyOnlyMsgId(state, action.id, (msg) => {
          const newMsg = { ...msg };
          newMsg.isJunk = action.isJunk;
          return newMsg;
        });
      }
      return state;
    }
```

which only changes the state if `action.isJunk == false`. Surely the state should be changed to match `action.isJunk`? Or does `markSelectedAsJunk` do modifications that get propagated and it ignores its parameter and only sets `isJunk = true`?

**Comment by Standard8** [comment]
> which only changes the state if `action.isJunk == false`. Surely the state should be changed to match `action.isJunk`? Or does `markSelectedAsJunk` do modifications that get propagated and it ignores its parameter and only sets `isJunk = true`?

Ah, I think it was probably trying to optimise for the case where junk would normally get moved to the junk folder straight away. However, as that might not be always true, I'm happy for that to change here.

**Review by Standard8 — APPROVED** [review]
Thank you, this looks good, nice to get cleaned up a bit more.

**Pull request merged**
